apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpc
  template:
    metadata:
      labels: gpc
    spec:
      containers:
      - name: gpc-gke
        image: gcr.io/$PROJECT_ID/gcp
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"